services:
  db:
    image: mariadb:latest
    container_name: multiverse-payroll-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-multiverse_db}
      MYSQL_USER: ${MYSQL_USER:-multiverse_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-multiverse_password}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - multiverse-network

volumes:
  db_data:
    driver: local

networks:
  multiverse-network:
    driver: bridge
